language: node_js
node_js: 8

install:
  - yarn

script:
  - yarn examples:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: examples/gh-pages
  on:
    branch: master

cache:
  yarn: true